name: Merge Approved Dependency PRs

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.review.state == "approved" && github.actor == "dependabot[bot]"
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: merge
      - run: gh pr merge --auto --squash --delete-branch "$PR_URL"
