name: Merge Approved Dependency PRs

on:
  pull_request_review:
    types: [submitted]

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.review.state === "approved"
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: merge
      - run: gh pr merge --auto --squash --delete-branch "$PR_URL"
